version: "3.8"
services:
  neo4j:
    image: neo4j:5
    container_name: graph-rag-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP (browser)
      - "7687:7687"   # Bolt (driver)
    environment:
      NEO4J_AUTH: neo4j/adwyteneo
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
